# Generated by Django 2.2.2 on 2019-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HulajnogaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('coordinateX', models.FloatField()),
                ('coordinateY', models.FloatField()),
                ('ideas_category', models.CharField(choices=[('High Curb', 'High Curb'), ('Cobblestones', 'Cobblestones'), ('Potholes', 'Potholes'), ('Dangerous Turn', 'Dangerous Turn'), ('Slippery Road', 'Slippery Road'), ('Many Pedestrians', 'Many Pedestrians'), ('Good Surface', 'Good Surface'), ('Wide Road', 'Wide Road'), ('Other', 'Other')], default='Other', max_length=20)),
                ('review_body', models.TextField()),
                ('adress', models.TextField()),
                ('influence_points', models.IntegerField(default=0)),
            ],
        ),
    ]
